-- MySQL Script generated by MySQL Workbench
-- 05/26/16 18:04:34
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`clinic`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`clinic` (
  `id` CHAR(5) NOT NULL,
  `name` VARCHAR(30) NOT NULL,
  `address` VARCHAR(30) NULL DEFAULT NULL,
  `phone` CHAR(8) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`doctor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`doctor` (
  `id` CHAR(8) NOT NULL,
  `name` VARCHAR(15) NOT NULL,
  `phone` CHAR(11) NULL DEFAULT NULL,
  `specialty` CHAR(15) NULL DEFAULT NULL,
  `clinic_id` CHAR(5) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_doctor_clinic1_idx` USING BTREE (`clinic_id` ASC),
  CONSTRAINT `fk_doctor_clinic1`
    FOREIGN KEY (`clinic_id`)
    REFERENCES `mydb`.`clinic` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`patient`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`patient` (
  `id` CHAR(8) NOT NULL,
  `age` INT(3) NOT NULL,
  `gender` TINYINT(1) NOT NULL,
  `name` VARCHAR(15) NOT NULL,
  `address` VARCHAR(30) NULL DEFAULT NULL,
  `phone` CHAR(11) NOT NULL,
  `doctor_id` CHAR(8) NULL DEFAULT NULL,
  `password` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_patient_doctor_idx` USING BTREE (`doctor_id` ASC),
  CONSTRAINT `fk_patient_doctor`
    FOREIGN KEY (`doctor_id`)
    REFERENCES `mydb`.`doctor` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`appointment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`appointment` (
  `id` CHAR(5) NOT NULL,
  `patient_id` CHAR(8) NOT NULL,
  `doctor_id` CHAR(8) NOT NULL,
  `clinic_id` CHAR(5) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_prescription_patient1_idx` (`patient_id` ASC),
  INDEX `fk_appointment_doctor1_idx` (`doctor_id` ASC),
  INDEX `fk_appointment_clinic1_idx` (`clinic_id` ASC),
  CONSTRAINT `fk_appointment_clinic1`
    FOREIGN KEY (`clinic_id`)
    REFERENCES `mydb`.`clinic` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_appointment_doctor1`
    FOREIGN KEY (`doctor_id`)
    REFERENCES `mydb`.`doctor` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_prescription_patient1`
    FOREIGN KEY (`patient_id`)
    REFERENCES `mydb`.`patient` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`request`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`request` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `date_prefer` DATE NOT NULL,
  `patient_id` CHAR(8) NOT NULL,
  `doctor_id` CHAR(8) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_request_patient1_idx` USING BTREE (`patient_id` ASC),
  INDEX `fk_request_doctor1_idx` USING BTREE (`doctor_id` ASC),
  CONSTRAINT `fk_request_doctor1`
    FOREIGN KEY (`doctor_id`)
    REFERENCES `mydb`.`doctor` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_request_patient1`
    FOREIGN KEY (`patient_id`)
    REFERENCES `mydb`.`patient` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 33
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`schedule`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`schedule` (
  `doctor_id` CHAR(8) NOT NULL,
  `date01` INT(1) NOT NULL DEFAULT '-1',
  `date02` INT(1) NOT NULL DEFAULT '-1',
  `date03` INT(1) NOT NULL DEFAULT '-1',
  `date04` INT(1) NOT NULL DEFAULT '-1',
  `date05` INT(1) NOT NULL DEFAULT '-1',
  `date06` INT(1) NOT NULL DEFAULT '-1',
  `date07` INT(1) NOT NULL DEFAULT '-1',
  `date08` INT(1) NOT NULL DEFAULT '-1',
  `date09` INT(1) NOT NULL DEFAULT '-1',
  `date10` INT(1) NOT NULL DEFAULT '-1',
  `date11` INT(1) NOT NULL DEFAULT '-1',
  `date12` INT(1) NOT NULL DEFAULT '-1',
  `date13` INT(1) NOT NULL DEFAULT '-1',
  `date14` INT(1) NOT NULL DEFAULT '-1',
  `date15` INT(1) NOT NULL DEFAULT '-1',
  `date16` INT(1) NOT NULL DEFAULT '-1',
  `date17` INT(1) NOT NULL DEFAULT '-1',
  `date18` INT(1) NOT NULL DEFAULT '-1',
  `date19` INT(1) NOT NULL DEFAULT '-1',
  `date20` INT(1) NOT NULL DEFAULT '-1',
  `date21` INT(1) NOT NULL DEFAULT '-1',
  `date22` INT(1) NOT NULL DEFAULT '-1',
  `date23` INT(1) NOT NULL DEFAULT '-1',
  `date24` INT(1) NOT NULL DEFAULT '-1',
  `date25` INT(1) NOT NULL DEFAULT '-1',
  `date26` INT(1) NULL DEFAULT '-1',
  `date27` INT(1) NOT NULL DEFAULT '-1',
  `date28` INT(1) NOT NULL DEFAULT '-1',
  `date29` INT(1) NOT NULL DEFAULT '-1',
  `date30` INT(1) NOT NULL DEFAULT '-1',
  `date31` INT(1) NOT NULL DEFAULT '-1',
  PRIMARY KEY (`doctor_id`),
  INDEX `fk_schedule_doctor1_idx` USING BTREE (`doctor_id` ASC),
  CONSTRAINT `fk_schedule_doctor1`
    FOREIGN KEY (`doctor_id`)
    REFERENCES `mydb`.`doctor` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

USE `mydb`;

DELIMITER $$
USE `mydb`$$
CREATE
DEFINER=`root`@`localhost`
TRIGGER `mydb`.`appointment_AFTER_INSERT`
AFTER INSERT ON `mydb`.`appointment`
FOR EACH ROW
BEGIN

END$$


DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
